mc: False
is_h4l: False
input_files:
  [
    "/Users/zhengqingwang/alice/data/derived/Hypertriton_2body/LHC23_PbPb_fullTPC/pass4/ep4/AO2D.root",
    # "/data3/fmazzasc/hyp_run_3/pbpb/custom_vertexer/zzh/AO2D_merg.root",
    # "/data3/fmazzasc/hyp_run_3/pbpb/custom_vertexer/zzk/AO2D_merg.root",
    # "/data3/fmazzasc/hyp_run_3/pbpb/custom_vertexer/zzk_bis/AO2D_merg.root",
    # "/data3/fmazzasc/hyp_run_3/pbpb/custom_vertexer/zzf/AO2D_merg.root",

  ]
output_dir: "../results/ep4"
output_file: "HypertritonResults_pbpb_builtin"
selection:
  {
    "fEta": "abs(fEta) < 0.9",
    "fPt": "fPt > 2.",
    "fCt": "fCt > 1",
    "fCosPA": "fCosPA > 0.9999",
    #"fCosPA": "fCosPA > 0.99995",
    "fNSigmaHe": "fNSigmaHe > -3",
    #"fDcaV0Daug": "abs(fDcaV0Daug) < 0.04",
    #"fDcaHe": "abs(fDcaHe) > 0.002",
    "fTPCsignalPi": "fTPCsignalPi < 1000.",
    "fNTPCclusHe": "fNTPCclusHe > 100",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fPtPi": "fPtPi < 1.5",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 4.",
    # "fCentralityFT0C" : "10 < fCentralityFT0C < 60",
    # "fTracked": "fTracked == 0",
    "fTPCChi2He": "fTPCChi2He > 0.5",
  }
is_matter: "both"
calibrate_he_momentum: False
skip_out_tree: False
do_signal_extraction: True
