mc: False
is_h4l: True
input_files:
  [
    "/data3/fmazzasc/hyp_run_3/pp2023/skimmed/AO2D.root",
    # "/data3/fmazzasc/hyp_run_3/pp2022/LHC22_highIR_thin_custom/AO2D.root",
    "/data3/fmazzasc/hyp_run_3/pp2024/ag/AO2D.root",
    "/data3/fmazzasc/hyp_run_3/pp2024/aj/AO2D.root",
    "/data3/fmazzasc/hyp_run_3/pp2024/af/AO2D.root",
    "/data3/fmazzasc/hyp_run_3/pp2024/al/AO2D.root"
  ]
output_dir: "../results/"
output_file: "HypertritonResults_24_apass4_sk_cal"
selection:
  {
    # "fEtaHe3" : "abs(fEtaHe3) < 0.9",
    # "fEtaPi" : "abs(fEtaPi) <   0.9",
    # "fNTPCclusHe": "fNTPCclusHe > 100",
    "fPt" : " fPt < 4.",
    "fCosPA": "fCosPA > 0.995",
    "fNSigmaHe": "fNSigmaHe > 1",
    # "fTracked": "fTracked == 1",  
      "fNSigmaHe4": "abs(fNSigmaHe4) < 2",
      # "fTPCsignalPi": "fTPCsignalPi < 1000.",
      # "fTPCmomHe": "fTPCmomHe > 0.5",
    "fAvgClSizeCosLambda": "fAvgClSizeCosLambda > 4",

  }
is_matter: "matter"
calibrate_he_momentum: True
skip_out_tree: True
do_signal_extraction: True