mc: False
is_h4l: True
input_files:
  [
    "/data3/fmazzasc/hyp_run_3/pbpb/pass3/AO2D.root"
  ]
output_dir: "../results/"
output_file: "HypertritonResults_pbpb_h4l"
selection:
  {
    "fPt": "fPt > 2. and fPt < 6",
    "fCt": "fCt > 1",
    "fCosPA": "fCosPA > 0.9995",
    "fNSigmaHe4": "fNSigmaHe4 > -1",
    "fTPCsignalPi": "fTPCsignalPi < 600.",
    "fNTPCclusHe": "fNTPCclusHe > 100",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 6",
    "fTPCsignalHe": "fTPCsignalHe < 600",
    # "fCentralityFT0C" : "10 < fCentralityFT0C < 60",
    # "fTracked": "fTracked == 0",
  }
is_matter: "both"
calibrate_he_momentum: False
skip_out_tree: False
