mc: False
is_h4l: True
input_files:
  [
    "/data3/fmazzasc/hyp_run_3/pp2024/ag/AO2D.root",
    "/data3/fmazzasc/hyp_run_3/pp2024/aj/AO2D.root",
    "/data3/fmazzasc/hyp_run_3/pp2024/af/AO2D.root",
    "/data3/fmazzasc/hyp_run_3/pp2024/al/AO2D.root"
  ]
output_dir: "../results/2024_analyse_tree/"
output_file: "HypertritonResults_h4l_24sk_custom"
selection:
  {
    "fDcaV0Daug": "abs(fDcaV0Daug) < 0.1",
    "fDcaHe": "abs(fDcaHe) > 0.004",
    "fDcaPi": "abs(fDcaPi) > 0.05",
    "fPt" : " fPt < 4",
    "fCosPA": "fCosPA > 0.999",
    "fNSigmaHe4": "abs(fNSigmaHe4) < 2",
    # "fTPCsignalPi": "fTPCsignalPi < 1000.",
    # "fTPCmomHe": "fTPCmomHe > 0.5",
    "fAvgClSizeCosLambda": "fAvgClSizeCosLambda > 6",

  }
is_matter: "both"
calibrate_he_momentum: True
skip_out_tree: True
do_signal_extraction: True