input_file_name_data: "/Users/zhengqingwang/alice/data/derived/Hypertriton_2body/LHC23_PbPb_fullTPC/pass4/ep4/AO2D.root"
input_file_name_mc: "/Users/zhengqingwang/alice/data/derived/Hypertriton_2body/LHC23_PbPb_fullTPC/mc/AO2D.root"
input_AnalysisResults_file_path: "/Users/zhengqingwang/alice/data/derived/Hypertriton_2body/LHC23_PbPb_fullTPC/pass4/ep4/AnalysisResults.root"
output_dir_name: "../results/ep4/lifetime"

pt_bins: [2, 3.5, 5, 8]
is_matter: "both"
pre_selection_method: "BDT" # BDT or topology
# sweights cows
method: "both"
signal_fit_func: "dscb"
bkg_fit_func: "pol2"
mass_range: [2.95, 3.05]
ct_range: [[2, 35], [2, 30], [2, 25]]
nctbins_acceptance: 50
sigma_range_mc_to_data: [[1., 1.5], [1., 1.5], [1., 1.5]]
nbins_plot_mc : 80
nbins_plot_data : 40
save_fit_results: True
silent_mode: False
eff_start: 0.5
eff_end: 0.99
neff_steps: 100

do_sys: false

new_training: true
opean_NSigmaH3_mc_shift: true
opean_NSigmaH3_data_shift: true
training_preselections: 'fPt>1 and fTPCsignalPi<1000 and abs(fNSigmaHe)<5 and fCosPA>0.99 and fCt<40'
training_variables: ['fDcaV0Daug', 'fDcaHe', 'fDcaPi', 'fCosPA', 'fNSigmaHe']
test_set_size: 0.5
bkg_fraction_max: 6
random_state: 42
hyperparams:
  max_depth: 5 # 5
  min_split_loss: 1.5 # 0.7
  learning_rate: 0.05
  n_estimators: 800
  min_child_weight: 3 # 3
  subsample: 0.70
  colsample_bytree: 0.73
  tree_method: 'hist'
  seed: 42

selection:
  [
    {
    "fPt": "fPt > 2",
    "fCt": "fCt > 1",
    "fCosPA": "fCosPA > 0.9999",
    "fNSigmaHe": "fNSigmaHe > -3",
    "fTPCsignalPi": "fTPCsignalPi < 1000.",
    "fNTPCclusHe": "fNTPCclusHe > 90",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 4.",
    "fTPCChi2He": "fTPCChi2He > 0.5",
    },
    {
    "fPt": "fPt > 2",
    "fCt": "fCt > 1",
    "fCosPA": "fCosPA > 0.9999",
    "fNSigmaHe": "fNSigmaHe > -3",
    "fTPCsignalPi": "fTPCsignalPi < 1000.",
    "fNTPCclusHe": "fNTPCclusHe > 90",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 4.",
    "fTPCChi2He": "fTPCChi2He > 0.5",
    },
    {
    "fPt": "fPt > 2",
    "fCt": "fCt > 1",
    "fCosPA": "fCosPA > 0.9999",
    "fNSigmaHe": "fNSigmaHe > -3",
    "fTPCsignalPi": "fTPCsignalPi < 1000.",
    "fNTPCclusHe": "fNTPCclusHe > 90",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 4.",
    "fTPCChi2He": "fTPCChi2He > 0.5",
    }
  ]

