input_file_name_data: "/Users/zhengqingwang/alice/data/derived/Hypertriton_2body/LHC23_PbPb_fullTPC/pass4/ep4/AO2D.root"
input_file_name_mc: "/Users/zhengqingwang/alice/data/derived/Hypertriton_2body/LHC23_PbPb_fullTPC/mc/AO2D.root"
output_dir_name: "../results/ep4/lifetime"

pt_bins: [2, 3.5, 5, 8]
is_matter: "both"
pre_selection_method: "topology" 
# sweights cows
method: "both"
signal_fit_func: "dscb"
bkg_fit_func: "pol2"
mass_range: [2.96, 3.04]
ct_range: [0, 40]
sigma_range_mc_to_data: [[1., 1.5], [1., 1.5], [1., 1.5]]
nbins_plot_mc : 80
nbins_plot_data : 40
save_fit_results: True

do_sys: false

training_variables: ['fDcaV0Daug', 'fDcaHe', 'fDcaPi', 'fCosPA', 'fNSigmaHe','fCt']
test_set_size: 0.5
background_over_signal_max: 6
random_state: 42
opean_NSigmaH3_signal_shift: True
hyperparams:
  max_depth: 5 # 5
  min_split_loss: 1.5 # 0.7
  learning_rate: 0.05
  n_estimators: 800
  min_child_weight: 3 # 3
  subsample: 0.70
  colsample_bytree: 0.73
  tree_method: 'hist'
  seed: 42

selection:
  [
    {
    "fPt": "fPt > 2",
    "fCt": "fCt > 1",
    "fCosPA": "fCosPA > 0.9999",
    "fNSigmaHe": "fNSigmaHe > -3",
    "fTPCsignalPi": "fTPCsignalPi < 1000.",
    "fNTPCclusHe": "fNTPCclusHe > 90",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 4.",
    "fTPCChi2He": "fTPCChi2He > 0.5",
    },
    {
    "fPt": "fPt > 2",
    "fCt": "fCt > 1",
    "fCosPA": "fCosPA > 0.9999",
    "fNSigmaHe": "fNSigmaHe > -3",
    "fTPCsignalPi": "fTPCsignalPi < 1000.",
    "fNTPCclusHe": "fNTPCclusHe > 90",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 4.",
    "fTPCChi2He": "fTPCChi2He > 0.5",
    },
    {
    "fPt": "fPt > 2",
    "fCt": "fCt > 1",
    "fCosPA": "fCosPA > 0.9999",
    "fNSigmaHe": "fNSigmaHe > -3",
    "fTPCsignalPi": "fTPCsignalPi < 1000.",
    "fNTPCclusHe": "fNTPCclusHe > 90",
    "fTPCmomHe": "fTPCmomHe > 1",
    "fAvgClusterSizeHe": "fAvgClusterSizeHe > 4.",
    "fTPCChi2He": "fTPCChi2He > 0.5",
    }
  ]

