## choose between matter, antimatter or both
matter_type: "antimatter"

## i/o
input_parquet_data : ['../results/training_test/dataH.parquet.parquet.gzip']
input_parquet_mc: '../results/HypertritonResults_MC.root.parquet'
input_analysis_results: '/data/shared/hyp_run_3/apass4/AnalysisResults.root'
output_dir : '../results/training_test'
output_file : 'fit_results_antimat.root'


preselections: "fIsMatter==False"
ml_efficiency_scan: True
input_eff_dir: "../results/training_test"
