mc: True
is_h4l: False
input_files: ["/data3/fmazzasc/hyp_run_3/mc/LHC23j6b/AO2D_h3l.root"]
output_dir: "../results/"
output_file: "HypertritonResults_23j6b_h3l"
selection: {
      "fEtaHe3" : "abs(fEtaHe3) < 0.9",
      "fEtaPi" : "abs(fEtaPi) < 0.9",
      "fNTPCclusPi": "fNTPCclusPi > 70",
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
}

is_matter: "both"
calibrate_he_momentum: True
skip_out_tree: True
do_signal_extraction: True