input_files_data:
  [
    "/data3/fmazzasc/hyp_run_3/pp2022/LHC22_new/AO2D.root",
  ]
input_files_mc: ["/data3/fmazzasc/mc_old/AO2D_h3l.root"]
input_analysis_results_file: "/data3/fmazzasc/hyp_run_3/pp2022/LHC22_new/AnalysisResults.root"
output_dir: "../results/2022_pt_analysis/"
is_trigger: False

output_file: "pt_analysis_antimat"
output_file_qa: "qa"

pt_bins: [1.5, 2., 2.5, 3.5, 5]
calibrate_he_momentum : True
bkg_fit_func: "pol1"
signal_fit_func: "dscb"
is_matter: "antimatter"
n_bins_mass_data: 3
n_bins_mass_mc: 80

selection:
  [
    {
      "fEtaHe3" : "abs(fEtaHe3) < 0.9",
      "fEtaPi" : "abs(fEtaPi) < 0.9",
      "fNTPCclusPi": "fNTPCclusPi > 70",
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
    },
    {
      "fEtaHe3" : "abs(fEtaHe3) < 0.9",
      "fEtaPi" : "abs(fEtaPi) < 0.9",
      "fNTPCclusPi": "fNTPCclusPi > 70",
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
    },
    {
      "fEtaHe3" : "abs(fEtaHe3) < 0.9",
      "fEtaPi" : "abs(fEtaPi) < 0.9",
      "fNTPCclusPi": "fNTPCclusPi > 70",
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
    },
    {
      "fEtaHe3" : "abs(fEtaHe3) < 0.9",
      "fEtaPi" : "abs(fEtaPi) < 0.9",
      "fNTPCclusPi": "fNTPCclusPi > 70",
      "fCosPA": "fCosPA > 0.99",
      "fNSigmaHe": "fNSigmaHe > -2.5",
      "fTPCsignalPi": "fTPCsignalPi < 1000."
    },
    
  ]

sigma_range_mc_to_data: [[1., 1.2], [1, 1.3], [1., 1.5], [1.5, 1.7]]


# absorption, event and signal loss corrections
absorption_histo_file: "../results/absorption/absorption_histos_x1.5.root"
event_loss: 0.83
signal_loss: 0.9

do_syst: False
n_trials: 1000
bkg_fit_func_syst: ["pol1", "expo"]
signal_fit_func_syst: ["dscb"]
cut_dict_syst:
  {
    "fCosPA": {"cut_greater": True, "cut_list": [0.985, 0.999, 50]},
     "fNSigmaHe": {"cut_greater": True, "cut_list": [-2.5, -1.5, 15]},
      "fTPCsignalPi": {"cut_greater": False, "cut_list": [1000, 1000, 1]},
    #  "fDcaV0Daug": {"cut_greater": False, "cut_list": [0.1, 0.5, 20]}
  }

absorption_syst: [0.03, 0.03, 0.03, 0.03]


