input_training_df_path: "/Users/zhengqingwang/alice/run3task/H3l_2body_spectrum/results/ep4/training_test"
input_mc_file_path: "/Users/zhengqingwang/alice/data/derived/Hypertriton_2body/LHC23_PbPb_fullTPC/mc/AO2D.root"
input_AnalysisResults_file_path: "/Users/zhengqingwang/alice/data/derived/Hypertriton_2body/LHC23_PbPb_fullTPC/pass4/ep4/AnalysisResults.root"
absorption_histo_file: "/Users/zhengqingwang/alice/run3task/H3l_2body_spectrum/results/absorption/absorption_histos_x1.5_pt_cen_50_80.root"

input_H3l_BWFit_file_path: "/Users/zhengqingwang/alice/run3task/H3l_2body_spectrum/H3l_2body_spectrum/utils/H3L_BWFit.root"

output_file_path: "/Users/zhengqingwang/alice/run3task/H3l_2body_spectrum/results/ep4/spec_train"
output_spectrm_file_name: "pt_analysis_pbpb"

# cen_bins: [0,5]
# pt_bins: [2, 3, 3.5, 4, 4.5, 5, 6, 8]
# cen_bins: [5,10]
# pt_bins: [2, 3, 3.5, 4, 4.5, 5, 6, 8]
# cen_bins: [10,30]
# pt_bins: [2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 8]
# cen_bins: [30,50]
# pt_bins: [2, 2.5, 3, 3.5, 4, 4.5, 5, 5.5, 6, 8]
cen_bins: [50,80]
pt_bins: [2, 2.5, 3, 3.5, 4, 4.5, 5, 8]

is_matter: "both"
bkg_fit_func: "pol2" 
signal_fit_func: "dscb"
sigma_range_mc_to_data: [1., 1.5]

do_syst: false
n_trials: 50
bkg_fit_func_syst: ["pol1", "expo"]
signal_fit_func_syst: ["dscb"]
bdt_numbers_syst: 50
absorption_syst: []

